##-- Carregando os dados e alocando em uma base local ----
##-- + Lendo as bases criadas ----
arqs_geral <- list.files(path = "dados/data/geral", full.names = T)[-1]
arqs_voronoi <- list.files(path = "dados/data/voronoy", full.names = T)
arqs_receitas <- list.files(path = "dados/data/receitas_despesas", full.names = T)
# names(arqs_geral) <- substr(x = basename(arqs), start = 1, nchar(basename(arqs))-4)
# names(arqs_voronoi) <- substr(x = basename(arqs_voronoi), start = 1, nchar(basename(arqs_voronoi))-4)
# names(arqs_receitas) <- substr(x = basename(arqs_receitas), start = 1, nchar(basename(arqs_receitas))-4)
##-- Salvando no base ----
con <- DBI::dbConnect(RSQLite::SQLite(), path = ":memory:")

dados <- readRDS(file = arqs_geral[1])
copy_to(con, dados, "dep_estadual", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_geral[2])
copy_to(con, dados, "dep_federal", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_geral[3])
copy_to(con, dados, "governador", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_geral[4])
copy_to(con, dados, "prefeito", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_geral[5])
copy_to(con, dados, "presidente", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_geral[6])
copy_to(con, dados, "senador", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_geral[7])
copy_to(con, dados, "vereador", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_voronoi[2])
copy_to(con, dados, "enderecos", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_voronoi[3])
copy_to(con, dados, "votos", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_receitas[1])
copy_to(con, dados, "despesa_part", temporary = FALSE, overwrite = TRUE)
rm(dados)
dados <- readRDS(file = arqs_receitas[2])
copy_to(con, dados, "receita_part", temporary = FALSE, overwrite = TRUE)
rm(dados)
##-- Consultando um candidato ----
chaves <- readRDS(file = "dados/data/geral/chaves.RDS")
chaves$ANO_ELEICAO <- as.numeric(chaves$ANO_ELEICAO)
chaves$DESCRICAO_CARGO <- toupper(chaves$DESCRICAO_CARGO)
copy_to(con, chaves, "chaves", temporary = FALSE, overwrite = TRUE)

vereador <- tbl(con, "vereador")
prefeito <- tbl(con, "prefeito")
governador <- tbl(con, "governador")
dep_estadual <- tbl(con, "dep_estadual")
dep_federal <- tbl(con, "dep_federal")
senador <- tbl(con, "senador")
presidente <- tbl(con, "presidente")
chaves <- tbl(con, "chaves")

enderecos <- tbl(con, "enderecos")
votos <- tbl(con, "votos")

despesa_part <- tbl(con, "despesa_part")
receita_part <- tbl(con, "receita_part")

lat_long <- readRDS(file = arqs_voronoi[1])